---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest

    - name: start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: copy html
      copy:
        src: files/index.html
        dest: /var/www/html/index.html

    - name: allow port 80 in ufw
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: show ip
      shell: echo "Server IP {{ ansible_default_ipv4.address }}"
      register: ip_output

    - name: display ip
      debug:
        msg: "{{ ip_output.stdout }}"
